
# Site settings
title: Zoe Huang
name: Zoe Huang
subtitle: Data Analyst
email: huangzichen0409@gmail.com
description: >
  Data Analyst
baseurl: ""
url: "https://pesoto.github.io/"
github_username:  Zoe0409
disqus_baseurl: "https://zoe0409.github.io"
disqus_shortname: https-zoe0409-github-io
permalink: :title

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Zoe Huang"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: GitHub
    icon: github
    username: pesoto
    url: https://github.com/Zoe0409
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: Zoe Huang
    url: https://www.linkedin.com/in/huang-zoe
    desc: Connect with me on LinkedIn
    share: true
